# Generated by Django 4.2.7 on 2023-11-29 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviexpress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('rut', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('subtotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('rut', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviexpress.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_uni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_empresa', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=30)),
                ('rubro', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviexpress.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horafecha', models.DateTimeField()),
                ('servicio', models.CharField(max_length=50)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviexpress.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRecepcion', models.DateTimeField()),
                ('orden_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviexpress.ordenpedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviexpress.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ordenpedido',
            name='productos',
            field=models.ManyToManyField(through='serviexpress.DetalleOrdenPedido', to='serviexpress.producto'),
        ),
        migrations.AddField(
            model_name='ordenpedido',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviexpress.proveedor'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('detalle', models.CharField(max_length=150)),
                ('totalPagar', models.IntegerField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviexpress.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='detalleordenpedido',
            name='orden_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviexpress.ordenpedido'),
        ),
        migrations.AddField(
            model_name='detalleordenpedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviexpress.producto'),
        ),
    ]
