# Generated by Django 4.2.7 on 2023-12-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviexpress', '0002_cliente_detalleordenpedido_empleado_ordenpedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
