# Generated by Django 4.2.7 on 2023-12-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviexpress', '0003_alter_cliente_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='username',
        ),
    ]
